version: '3'

services:
  backend:
    container_name: portfolio_backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
       - ./:/backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: 
      - ./.env
