# Generated by Django 3.2.2 on 2021-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Test', max_length=75),
            preserve_default=False,
        ),
    ]
