# Generated by Django 3.2.2 on 2021-06-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
