# Generated by Django 3.2.2 on 2021-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.JSONField(default={'en': 'MDX', 'fr': 'MDX'}, verbose_name='name'),
            preserve_default=False,
        ),
    ]
