# Generated by Django 3.2.2 on 2021-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210622_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.JSONField(default=[6, 2021]),
            preserve_default=False,
        ),
    ]
