# Generated by Django 3.2.2 on 2021-06-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.technology'),
        ),
    ]
