# Generated by Django 3.2.2 on 2021-06-23 05:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skill_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.technology_file_path),
        ),
    ]
