# Generated by Django 3.2.2 on 2021-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
