# Generated by Django 3.2.5 on 2021-07-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripiton',
            new_name='description',
        ),
    ]
