# Generated by Django 3.2.5 on 2021-07-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
