# Generated by Django 3.2.5 on 2021-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210716_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
