# Generated by Django 3.2.5 on 2021-08-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='message',
        ),
    ]
