# Generated by Django 3.2.5 on 2021-08-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_review_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.JSONField(default={'en': 'Test messqg\x08\x08ag\x08', 'fr': ''}),
            preserve_default=False,
        ),
    ]
