# Generated by Django 3.2.5 on 2021-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.JSONField(default={'en': '', 'fr': ''}),
        ),
    ]
