# Generated by Django 3.2.5 on 2021-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.JSONField(default=dict),
        ),
    ]
